from datetime import datetime
import json
import math
from pathlib import Path
import re
import textwrap


BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent
OUTPUT_DIR = PROJECT_ROOT / 'output'

PAGE_WIDTH = 612
PAGE_HEIGHT = 792
MARGIN_LEFT = 54
MARGIN_RIGHT = 72
MARGIN_TOP = 64
MARGIN_BOTTOM = 64
LINE_HEIGHT = 13

# Approximate Courier glyph width in points at font size 10.
CHAR_WIDTH = 5.2


def _pdf_escape(text: str):
    return text.replace('\\', '\\\\').replace('(', '\\(').replace(')', '\\)')


def _sanitize_filename_part(value: str):
    return re.sub(r'[^A-Za-z0-9._-]+', '_', value).strip('_') or 'unknown'


def _format_value(value):
    if isinstance(value, float):
        return f'{value:.6f}'
    return str(value)


def _to_pretty_lines(value):
    payload = json.dumps(value, indent=2, ensure_ascii=True, default=str, sort_keys=True)
    return payload.splitlines()


def _render_table(title, rows, key_header='Item', value_header='Value', key_width=34, value_width=52):
    lines = [title, '-' * len(title)]
    if not rows:
        lines.append('No data available.')
        lines.append('')
        return lines

    border = f'+{"-" * (key_width + 2)}+{"-" * (value_width + 2)}+'
    header = f'| {key_header.ljust(key_width)} | {value_header.ljust(value_width)} |'
    lines.extend([border, header, border])

    for key, value in rows:
        key_text = str(key)
        value_text = _format_value(value)
        key_chunks = textwrap.wrap(key_text, width=key_width) or ['']
        value_chunks = textwrap.wrap(value_text, width=value_width) or ['']
        row_count = max(len(key_chunks), len(value_chunks))
        for i in range(row_count):
            left = key_chunks[i] if i < len(key_chunks) else ''
            right = value_chunks[i] if i < len(value_chunks) else ''
            lines.append(f'| {left.ljust(key_width)} | {right.ljust(value_width)} |')
        lines.append(border)

    lines.append('')
    return lines


def _build_report_lines(model_name: str, instrument_id: str, input_payload, output_payload, extra_sections=None):
    issue_date = input_payload.get('issue_date', 'N/A') if isinstance(input_payload, dict) else 'N/A'
    maturity_date = input_payload.get('maturity_date', input_payload.get('end_date', 'N/A')) if isinstance(input_payload, dict) else 'N/A'
    currency = input_payload.get('currency', 'N/A') if isinstance(input_payload, dict) else 'N/A'

    lines = [
        f'Pricing Report for {instrument_id}',
        '',
        'Scope',
        '-----',
        (
            'This report summarizes the pricing setup and model outputs generated by the '
            f'Quantyx pricer using the {model_name} model.'
        ),
        '',
    ]

    facts_rows = [
        ('Instrument', instrument_id),
        ('Model', model_name),
        ('Currency', currency),
        ('Issue date', issue_date),
        ('Maturity date', maturity_date),
        ('Report generated', datetime.now().isoformat(timespec='seconds')),
    ]
    lines.extend(_render_table('Instrument Facts', facts_rows))

    output_rows = []
    if isinstance(output_payload, dict):
        for key in [
            'discount_curve_name',
            'valuation_mode',
            'selected_call_date',
            'selected_npv',
            'npv_to_first_call',
            'npv_to_worst_call',
            'npv_to_maturity',
            'model_ytm_to_maturity',
            'spread_bp',
            'evaluation_date',
        ]:
            if key in output_payload:
                output_rows.append((key, output_payload.get(key)))

        hw_params = output_payload.get('hw_parameters')
        if isinstance(hw_params, dict):
            output_rows.append(('hw_a', hw_params.get('a')))
            output_rows.append(('hw_sigma', hw_params.get('sigma')))
            output_rows.append(('hw_source', hw_params.get('source')))
            output_rows.append(('hw_vol_surface', hw_params.get('vol_surface_name')))
            output_rows.append(('hw_rmse', hw_params.get('rmse')))

    lines.extend(_render_table('Pricing Output Summary', output_rows, key_header='Output', value_header='Value'))

    # SPIRE-specific output expansion: include PV decomposition values in report
    if model_name.lower() == 'spire' and isinstance(output_payload, dict):
        price_pct = output_payload.get('price_pct', {})
        spire_rows = []
        # Prefer percentage-formatted outputs when available
        def pct(key):
            return price_pct.get(key) if key in price_pct else output_payload.get(key)

        spire_rows.append(('PV(Note) %', pct('pv_note')))
        spire_rows.append(('PV(Note) to_call %', pct('pv_note_to_call')))
        spire_rows.append(('PV(Note) to_worst %', pct('pv_note_to_worst')))
        spire_rows.append(('PV(Note) to_maturity %', pct('pv_note_to_maturity') or pct('pv_note')))
        spire_rows.append(('PV(Collateral) %', pct('pv_collateral')))
        spire_rows.append(('PV(Collateral model estimate) %', pct('pv_collateral_model')))
        spire_rows.append(('Collateral valuation method', output_payload.get('collateral_valuation_method')))
        spire_rows.append(('PV(Swap) %', pct('pv_swap') or output_payload.get('pv_swap')))

        lines.extend(_render_table('SPIRE PV Breakdown', spire_rows, key_header='Output', value_header='Value'))

    # index_linked-specific output expansion: include PV decomposition and YTM
    if model_name.lower() == 'index_linked' and isinstance(output_payload, dict):
        price_pct = output_payload.get('price_pct', {})
        idx_rows = []
        def pct(key):
            return price_pct.get(key) if key in price_pct else output_payload.get(key)

        idx_rows.append(('PV(Note) %', pct('pv_note') or output_payload.get('pv_note')))
        idx_rows.append(('  - Coupons %', pct('pv_note_coupons') or output_payload.get('pv_note_coupons')))
        idx_rows.append(('  - Redemption %', pct('pv_note_redemption') or output_payload.get('pv_note_redemption')))
        idx_rows.append(('Yield to Maturity', output_payload.get('yield_to_maturity')))
        idx_rows.append(('PV(Collateral) %', pct('pv_collateral') or output_payload.get('pv_collateral')))
        idx_rows.append(('PV(Collateral model estimate) %', pct('pv_collateral_model') or output_payload.get('pv_collateral_model')))
        idx_rows.append(('Collateral valuation method', output_payload.get('collateral_valuation_method')))
        idx_rows.append(('PV(Swap) %', pct('pv_swap') or output_payload.get('pv_swap')))
        # adjustments
        idx_rows.append(('PV(Fees) %', pct('pv_fees') or (output_payload.get('pv_adjustments') or {}).get('pv_fees')))
        idx_rows.append(('PV(Funding) %', pct('pv_funding') or (output_payload.get('pv_adjustments') or {}).get('pv_funding')))
        idx_rows.append(('PV(CSA) %', pct('pv_csa') or (output_payload.get('pv_adjustments') or {}).get('pv_csa')))
        idx_rows.append(('PV(Residual Basis) %', pct('pv_residual_basis') or (output_payload.get('pv_adjustments') or {}).get('pv_residual_basis')))
        idx_rows.append(('PV(Adjustments Total) %', pct('pv_total_adjustments') or (output_payload.get('pv_adjustments') or {}).get('pv_total_adjustments')))

        lines.extend(_render_table('Index-Linked PV Breakdown', idx_rows, key_header='Output', value_header='Value'))

    if extra_sections:
        for section_title, section_payload in extra_sections:
            lines.extend(['', section_title, '-' * len(section_title)])
            lines.extend(_to_pretty_lines(section_payload))

    return lines


def _paginate_lines(lines, width, lines_per_page):
    wrapped = []
    for raw_line in lines:
        chunks = textwrap.wrap(raw_line, width=width) or ['']
        wrapped.extend(chunks)

    pages = []
    for i in range(0, len(wrapped), lines_per_page):
        pages.append(wrapped[i:i + lines_per_page])

    return pages or [['']]


def _build_pdf_bytes(pages_lines, start_x, start_y, line_height):
    objects = []

    # 1: Catalog, 2: Pages, 3: Font
    objects.append((1, b'<< /Type /Catalog /Pages 2 0 R >>'))

    page_count = len(pages_lines)
    kids = []
    page_obj_numbers = []
    content_obj_numbers = []

    for idx in range(page_count):
        page_obj = 4 + 2 * idx
        content_obj = page_obj + 1
        page_obj_numbers.append(page_obj)
        content_obj_numbers.append(content_obj)
        kids.append(f'{page_obj} 0 R')

    kids_str = ' '.join(kids)
    objects.append((2, f'<< /Type /Pages /Kids [ {kids_str} ] /Count {page_count} >>'.encode('ascii')))
    objects.append((3, b'<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'))

    for idx, lines in enumerate(pages_lines):
        page_obj = page_obj_numbers[idx]
        content_obj = content_obj_numbers[idx]

        content_lines = ['BT', '/F1 10 Tf', f'{line_height} TL', f'{start_x} {start_y} Td']
        for line in lines:
            content_lines.append(f'({_pdf_escape(line)}) Tj')
            content_lines.append('T*')
        content_lines.append('ET')
        content_stream = ('\n'.join(content_lines) + '\n').encode('ascii', errors='ignore')
        content_dict = f'<< /Length {len(content_stream)} >>\nstream\n'.encode('ascii') + content_stream + b'endstream'

        page_dict = (
            f'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_WIDTH} {PAGE_HEIGHT}] '
            f'/Resources << /Font << /F1 3 0 R >> >> /Contents {content_obj} 0 R >>'
        ).encode('ascii')

        objects.append((page_obj, page_dict))
        objects.append((content_obj, content_dict))

    objects.sort(key=lambda item: item[0])

    header = b'%PDF-1.4\n'
    body = bytearray()
    offsets = [0]

    for obj_num, obj_content in objects:
        offsets.append(len(header) + len(body))
        body.extend(f'{obj_num} 0 obj\n'.encode('ascii'))
        body.extend(obj_content)
        body.extend(b'\nendobj\n')

    xref_offset = len(header) + len(body)
    xref = bytearray()
    xref.extend(f'xref\n0 {len(offsets)}\n'.encode('ascii'))
    xref.extend(b'0000000000 65535 f \n')
    for offset in offsets[1:]:
        xref.extend(f'{offset:010d} 00000 n \n'.encode('ascii'))

    trailer = (
        f'trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\n'
        f'startxref\n{xref_offset}\n%%EOF\n'
    ).encode('ascii')

    return header + bytes(body) + bytes(xref) + trailer


def create_pdf_report(model_name: str, instrument_id: str, input_payload, output_payload, extra_sections=None):
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    safe_instrument = _sanitize_filename_part(instrument_id or 'unknown')
    pdf_path = OUTPUT_DIR / f'{safe_instrument}.pdf'

    printable_width_points = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT
    max_chars_per_line = max(60, int(math.floor(printable_width_points / CHAR_WIDTH)))
    printable_height_points = PAGE_HEIGHT - MARGIN_TOP - MARGIN_BOTTOM
    lines_per_page = max(20, int(math.floor(printable_height_points / LINE_HEIGHT)))

    lines = _build_report_lines(model_name, instrument_id, input_payload, output_payload, extra_sections=extra_sections)
    pages = _paginate_lines(lines, width=max_chars_per_line, lines_per_page=lines_per_page)
    pdf_bytes = _build_pdf_bytes(
        pages,
        start_x=MARGIN_LEFT,
        start_y=PAGE_HEIGHT - MARGIN_TOP,
        line_height=LINE_HEIGHT,
    )
    with open(pdf_path, 'wb') as f:
        f.write(pdf_bytes)

    return pdf_path